config/routes.rb
Rails.application.routes.draw do
  resources :users
  get "bmi", to: "bmi#index"

  get "/hello_world", to: "pages#hello"
  resources :posts
  resources :users

  mount Api::Test => '/api'

  resources :candidates do
    member do
      post :vote
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
    has_many :vote_logs, dependent: :destroy
end

app/models/store.rb
class Store < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
    has_one :store
    
    validate :name_validator

    before_create :encrypt_email

    private
    def name_validator
        unless name.starts_with? 'Ruby'
            errors[:name] << "必須是 Ruby 開頭喔！"
        end
    end

    def encrypt_email
        self.email = Digest::MD5.hexdigest(email)
    end
end

app/models/vote_log.rb
class VoteLog < ActiveRecord::Base
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bmi_controller.rb
# class BmiController < ApplicationController
#   def index
#   end
# end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_action :find_candidate, only: [:edit, :update, :destroy, :vote]

    def index
        @candidates = Candidate.all
    end

    def new
        @candidate = Candidate.new
    end

    def create
        @candidate = Candidate.new(candidate_params)

        if @candidate.save
            # success
            redirect_to candidates_path, notice: "Add candidate success!"
        else
            # fail
            render :new
        end
    end

    def edit
    end

    def update
        if @candidate.update(candidate_params)
            # success
            redirect_to candidates_path, notice: "Update candidate success!"
        else
            # fail
            render :eidt
        end
    end

    def destroy
        @candidate.destroy if @candidate
        redirect_to candidates_path, notice: "Delete candidate success!"
    end

    def vote
        # @candidate.increment(:votes)
        # @candidate.save
        @candidate.vote_logs.create(ip_address: request.remote_ip) if @candidate
        redirect_to candidates_path, notice: "Finished vote!"
    end

    private
    def candidate_params
        params.require(:candidate).permit(:name, :age, :party, :politics)
    end

    def find_candidate
        @candidate = Candidate.find_by(id: params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def hello
        render plain: params
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
      format.html { render :index }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :tel)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bmi_helper.rb
module BmiHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bmi/index.html.erb
<h1>BMI 計算機</h1>

<%= form_tag '/bmi/result' do %>
  身高：<%= text_field_tag 'body_height' %> 公分<br />
  體重：<%= text_field_tag 'body_weight' %> 公斤<br />
  <%= submit_tag "開始計算" %>
<% end %>

app/views/candidates/_form.html.erb
<%= form_for(candidate) do |f| %>
  <%= f.label :name, "姓名" %>
  <%= f.text_field :name %> <br />

  <%= f.label :age, "年齡" %>
  <%= f.text_field :age %> <br />

  <%= f.label :party, "政黨" %>
  <%= f.text_field :party %> <br />

  <%= f.label :politics, "政見" %>
  <%= f.text_area :politics %> <br />

  <%= f.submit %>
<% end %>

app/views/candidates/edit.html.erb
<h1>編輯候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/candidates/index.html.erb
<h1>候選人列表</h1>

<%= link_to "新增候選人", new_candidate_path %>

<table>
  <thead>
    <tr>
      <td>投票</td>
      <td>候選人姓名</td>
      <td>政黨</td>
      <td>政見</td>
      <td>得票數</td>
      <td>處理</td>
    </tr>
  </thead>
  <tbody>
    <% @candidates.each do |candidate| %>
    <tr>
      <td><%= link_to "投給這位", vote_candidate_path(candidate), method: "post", data: { confirm: "確定投給這個人?" } %></td>
      <td><%= candidate.name %>(年齡：<%= candidate.age %> 歲)</td>
      <td><%= candidate.party %></td>
      <td><%= candidate.politics %></td>
      <td><%= candidate.vote_logs.size %></td>
      <td>
        <%= link_to "編輯", edit_candidate_path(candidate) %>
        <%= link_to "刪除", candidate_path(candidate), method: "delete", data: { confirm: "確認刪除" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/candidates/new.html.erb
<h1>新增候選人</h1>

<%= render "form", candidate: @candidate %>

<br />
<%= link_to '回候選人列表', candidates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= notice %>
  <%= yield %>

</body>
</html>

app/views/pages/hello.html.erb
<h1>你好，世界</h1>
<h2>我是設計師也看得懂的檔案喔</h2>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :tel %><br>
    <%= f.text_field :tel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Tel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.tel %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @user.tel %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>